Vagrant.configure("2") do |config|
  config.vm.provision "shell" , inline: "echo hello"

  config.vm.define "VM3" do |config|
  config.vm.box = "bento/ubuntu-22.04"
  config.vm.hostname = "mysql"
  config.vm.network "private_network", ip: "192.168.50.41"
  
  config.vm.provision "file", source: "C:/vagrant4/mysql_init.sh", destination: "/tmp/mysql_init.sh"
  config.vm.provision "shell", inline: <<-SHELL
 
    sudo apt-get update
    sudo apt install net-tools -y
    sudo apt install stress -y
    sudo apt-get install mysql-server -y
    sudo groupadd --system prometheus
    sudo useradd -s /sbin/nologin --system -g prometheus prometheus
    curl -s https://api.github.com/repos/prometheus/mysqld_exporter/releases/latest   | grep browser_download_url   | grep linux-amd64 | cut -d '"' -f 4   | wget -qi -
    tar xvf mysqld_exporter*.tar.gz
    sudo mv  mysqld_exporter-*.linux-amd64/mysqld_exporter /usr/local/bin/
    sudo chmod +x /usr/local/bin/mysqld_exporter
    sudo bash -c "cat > /etc/.mysqld_exporter.cnf <<-EOF
[client]
user=mysqld_exporter
password=asd123
EOF"
    sudo chown root:prometheus /etc/.mysqld_exporter.cnf
    sudo bash -c "cat > /etc/systemd/system/mysql_exporter.service <<-EOF
    [Unit]
Description=Prometheus MySQL Exporter
After=network.target
User=prometheus
Group=prometheus

[Service]
Type=simple
Restart=always
ExecStart=/usr/local/bin/mysqld_exporter \
--config.my-cnf /etc/.mysqld_exporter.cnf \
--collect.global_status \
--collect.info_schema.innodb_metrics \
--collect.auto_increment.columns \
--collect.info_schema.processlist \
--collect.binlog_size \
--collect.info_schema.tablestats \
--collect.global_variables \
--collect.info_schema.query_response_time \
--collect.info_schema.userstats \
--collect.info_schema.tables \
--collect.perf_schema.tablelocks \
--collect.perf_schema.file_events \
--collect.perf_schema.eventswaits \
--collect.perf_schema.indexiowaits \
--collect.perf_schema.tableiowaits \
--collect.slave_status \
--web.listen-address=192.168.50.41:9104

[Install]
WantedBy=multi-user.target
EOF"
    mysqld_exporter  --version
    sudo systemctl daemon-reload
    sudo systemctl enable mysql_exporter
    sudo systemctl start mysql_exporter
    sudo systemctl start mysql
    sudo apt-get install prometheus-node-exporter -y
    sudo bash /tmp/mysql_init.sh
    

  SHELL
  end

  config.vm.define "VM4" do |config|
  config.vm.box = "bento/ubuntu-22.04"
  config.vm.hostname = "alert"
  config.vm.network "private_network", ip: "192.168.50.42"
  
  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update
    sudo apt install net-tools -y
    echo 'deb http://deb.robustperception.io/ precise nightly' | sudo tee -a /etc/apt/sources.list
    wget https://s3-eu-west-1.amazonaws.com/deb.robustperception.io/41EFC99D.gpg
    sudo apt-key add 41EFC99D.gpg
    sudo apt-get install prometheus -y
    sudo systemctl status prometheus
    wget -q -O - https://packages.grafana.com/gpg.key | gpg --dearmor | sudo tee /usr/share/keyrings/grafana.gpg > /dev/null
    echo "deb [signed-by=/usr/share/keyrings/grafana.gpg] https://packages.grafana.com/oss/deb stable main" | sudo tee -a /etc/apt/sources.list.d/grafana.list
    sudo apt update
    sudo apt install grafana -y
    sudo systemctl start grafana-server
    sudo systemctl enable grafana-server
    sudo systemctl status grafana-server
    wget https://github.com/prometheus/alertmanager/releases/download/v0.26.0/alertmanager-0.26.0.linux-amd64.tar.gz
    tar -xvzf alertmanager-0.26.0.linux-amd64.tar.gz
    sudo mv alertmanager-0.26.0.linux-amd64/alertmanager /usr/local/bin/
    sudo touch /etc/prometheus/alertmanager.yml
    sudo bash -c "cat > /etc/prometheus/alertmanager.yml <<-EOF
global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 10s
  receiver: 'email'
receivers:
- name: 'email'
  email_configs:
  - to: 'olesias897@gmail.com'
    from: 'olesias897@gmail.com'
    smarthost: smtp.gmail.com:587
    auth_username: 'olesias897@gmail.com'
    auth_identity: 'olesias897@gmail.com'
    auth_password: 'zvck pdue bagy uhao'
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']
EOF"
    sudo touch /etc/systemd/system/alertmanager.service
    sudo bash -c "cat > /etc/systemd/system/alertmanager.service <<-EOF
[Unit]
Description=AlertManager Server Service
Wants=network-online.target
After=network-online.target

[Service]
User=root
Group=root
Type=simple
ExecStart=/usr/local/bin/alertmanager --config.file /etc/prometheus/alertmanager.yml --web.external-url=http://192.168.50.42:9093


[Install]
WantedBy=multi-user.target
EOF"
  sudo systemctl daemon-reload
  sudo systemctl start alertmanager
  sudo systemctl enable alertmanager
  sudo systemctl status alertmanager
  sudo rm -rf /etc/prometheus/prometheus.yml
  sudo touch /etc/prometheus/prometheus.yml
  sudo bash -c "cat > /etc/prometheus/prometheus.yml <<-EOF
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.

  external_labels:
      monitor: 'example'

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets: ['localhost:9093']

rule_files:
    - "alert.rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'

    scrape_interval: 5s
    scrape_timeout: 5s

    static_configs:
      - targets: ['192.168.50.42:9090']

  - job_name: node
    static_configs:
      - targets: ['192.168.50.41:9100']
  - job_name: mysql
    static_configs:
      - targets: ['192.168.50.41:9104']
EOF"
      sudo touch /etc/prometheus/alert.rules.yml
      sudo bash -c "cat > /etc/prometheus/alert.rules.yml <<-EOF 
groups:
- name: alert.rules
  rules:
  - alert: CPUAlert
    expr: 100 * avg(1 - rate(node_cpu_seconds_total{mode='idle'}[1m])) by (instance) > 10
    for: 10s
    labels:
      severity: 'critical'
    annotations:
      summary: 'Hello alert appeared'
      description: 'CPU > 10%'
EOF"

     sudo touch /etc/systemd/system/prometheus.service
    sudo bash -c "cat > /etc/systemd/system/prometheus.service <<-EOF  
[Unit]
Description=Prometheus
Wants=network-online.target
After=network-online.target

[Service]
User=prometheus
Group=prometheus
Type=simple
ExecStart=/usr/bin/prometheus \
    --config.file /etc/prometheus/prometheus.yml \
    --storage.tsdb.path /var/lib/prometheus/ \
    --web.console.templates=/etc/prometheus/consoles \
    --web.console.libraries=/etc/prometheus/console_libraries

[Install]
WantedBy=multi-user.target
EOF"


    sudo systemctl restart prometheus
    sudo systemctl status prometheus
    promtool check rules /etc/prometheus/alert.rules.yml

  SHELL
  end
end